name: AbiBreaker

on:
  pull_request:
    paths:
      - 'abi-breaks/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pylint
        python3 -m pip install pyelftools
    - name: Analysing the code with pylint
      run: |
        cd abi-breaks
        ./style_check.sh
    - name: Code tests
      run: |
        cd abi-breaks
        ./unittests.py
